#+TITLE: PlaneSense
#+AUTHOR: 

* Purpose
To enable pilots to hear planes around them.

* Dependencies

** Supported OSes
Currently only gnu/linux is supported.
Any version of gnu/linux made in this decade should work.
** Requirements
- A recent version of Go must be installed. We used 1.6.2.
- An internet connection.

** Go Set up
- Ensure that your go path and bin are set via the environment variables.
- For example, adding the following to ones .bashrc will work. (Assuming one is using bash as a shell.)
  #+BEGIN_SRC bash
export GOPATH=$HOME/go
export PATH=$PATH:/home/<user>/go/bin/
  #+END_SRC
** To get the libsox library to work
- enable source repos in your distribution.
  - This can be done either be uncommenting the source in /etc/apt/sources.list, 
    and running sudo apt-get update
  - Or using the gui.
- Then install libsox
  - sudo apt-get install libsox-dev libsox2
- sudo apt-get build-deps sox
- sudo apt-get source sox
- cd into the dirctory apt-get created (It'll be sox-XXXX).
- sudo ./confiure
- sudo make -s
- sudo make install
- go get -u github.com/krig/go-sox

  
* Running
#+BEGIN_SRC bash
 % cd ./GoPositionalAudio 
 % go run sound.go
#+END_SRC

* Important files
Inside the GoPositionalAudio folder
- sound.go :: Main driver and implementation
